from pydantic import BaseModel, Field
from datetime import datetime

class QueryRequest(BaseModel):
    model: str = Field(..., description="The OpenAI model to use for the query.")
    query: str = Field(..., description="The user's text query.")
    temperature: float = Field(0.7, description="The temperature parameter for the OpenAI model. Higher values result in more creative responses.")
    max_tokens: int = Field(256, description="The maximum number of tokens to generate in the response.")

class QueryResponse(BaseModel):
    id: int = Field(..., description="Unique identifier for the query.")
    model: str = Field(..., description="The OpenAI model used for the query.")
    query: str = Field(..., description="The user's text query.")
    response: str = Field(..., description="The response generated by the OpenAI model.")
    created_at: datetime = Field(..., description="Timestamp when the query was created.")